version = 1

[[analyzers]]
name = "php"

[[analyzers]]
name = "shell"

[[analyzers]]
name = "javascript"

  [analyzers.meta]
  plugins = ["vue"]

[[analyzers]]
name = "python"

  [analyzers.meta]
  runtime_version = "3.x.x"